services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=kicau_user
      - POSTGRES_PASSWORD=kicau_password
      - POSTGRES_DB=kicau_db
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kicau_user -d kicau_db"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  backend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    network_mode: "host"  
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://kicau_user:kicau_password@localhost:5432/kicau_db?schema=public
      - PYTHON_BACKEND_URL=http://127.0.0.1:8000 
    restart: unless-stopped
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-kicau
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kicau.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped
    profiles:
      - admin

volumes:
  postgres: